security:
  basic:
    enabled: true
  user:
    name: user
    password: password

spring:
  application:
    name: spring-cloud-zuul
    
server:
  port: 8003

management: # spring-boot-starter-acturator
  port: 8001
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}

zuul:
  routes:
    vsl-ba:
      path: /vsl-ba/**
      service-id: tech-integration-vsl-ba
    spl-dg:
      path: /spl-dg/**
      service-id: tech-integration-spl-dg
