security:
  basic:
    enabled: true
  user:
    name: user
    password: password

spring:
  application:
    name: spring-cloud-zuul
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/psa_security_demo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    max-active: 100
    min-idle: 10
    min-evictable-idle-time-millis: 1800000
    test-on-borrow: true
    test-on-return: true
    test-while-idle: true
    validation-query: select 1
  jpa:
    generate: true
    show-sql: true
    properties.hibernate.format_sql: true
    
server:
  port: 8003

management: # spring-boot-starter-acturator
  port: 8001
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}

zuul:
  routes:
    vsl-ba:
      path: /api-vsl/**
      service-id: tech-integration-vsl
    spl-dg:
      path: /api-spl/**
      service-id: tech-integration-spl
      
tech:
  security:
    browser:
      initLoginPage: /authentication/require
      loginPage: /tech-signin.html
      loginProcessingUrl: /authentication/form
    loginType: REDIRECT
    validateCode:
      imageCode:
        width: 200
        height: 40
        length: 4
        expireIn: 60
        imageCodeUrl: /code/image
        filterUrls: /authentication/form,/user/getUser
